name: HelloWorld CL build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Get my code
      uses: actions/checkout@v3
    - name: List files
      run: ls -al
    - name: Build my files
      run: |
        cd HelloWorldCommandLine
        ls -al
        g++ -v
        g++ main.cpp -o main
    - name: Run my file
      run: ./main
