name: My QT windows build

on:
  push:
    branches:
      - 'master'
      - 'continuous-integration'
  workflow_dispatch:
    

defaults:
  run:
    shell: cmd

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   6.5.3

jobs:
  build:
    runs-on:  windows-latest

    steps:
      - name: (1) Checkout repo
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          aqtversion: '==3.1.*'
          version: '6.5.3'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_mingw'
          modules: 'qtcharts'
          tools: 'tools_mingw90'

      - name: (3) Create build directory
        run:  mkdir ${{ runner.temp }}\build

      - name: (3) Create deploy directory
        run:  mkdir ${{ runner.temp }}\deploy

      - name: (5) Build
        working-directory: ${{ runner.temp }}\build
        run:  |
              qmake -r ${{ env.SOURCE_DIR }}\TestHelloWorld\TestHelloWorld.pro
              gcc --version
              mingw32-make.exe -j8

      - name: dir after make
        working-directory: ${{ runner.temp }}\build
        run: dir /s

      - name: my deploy
        working-directory: ${{ runner.temp }}\build\release
        run: |
          windeployqt --dir ${{ runner.temp }}\deploy --no-translations TestHelloWorld.exe
          copy TestHelloWorld.exe ${{ runner.temp }}\deploy\TestHelloWorld.exe

      - name: dir before run
        working-directory: ${{ runner.temp }}\deploy
        run: dir /s
        
      - name: my run
        working-directory: ${{ runner.temp }}\deploy
        run: |
          dir
          TestHelloWorld -txt
          sleep 1

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: my-artifact
      #     path: ${{ runner.temp }}\deploy

